### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/webtorrent-hybrid#29]
Fresh install of webtorrent-hybrid globally as CLI

`webtorrent-hybrid seed awakening-new-zealand-4k.mp4`

DEBUG INFO: webtorrent-cli 1.1.1, webtorrent 0.88.3, node v4.4.2, linux x64, exit 1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)

**Comment by NTag** [comment]
Same issue here with `webtorrent-hybrid seed my-movie.mp4`:

```
DEBUG INFO: webtorrent-cli 1.1.1, webtorrent 0.88.3, node v5.10.1, linux x64, exit 1
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:890:11)
    at WriteWrap.afterWrite (net.js:767:14)
```

**Comment by Eibriel** [comment]
Same here:

```
fetching torrent metadata from 0 peers

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent-cli 1.1.3, webtorrent 0.91.1, node v5.11.0, linux x64, exit 1
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:893:11)
    at WriteWrap.afterWrite (net.js:783:14)
```

Dockerfile:
```
FROM ubuntu:14.04.3
RUN apt-get update && apt-get -y install vim git curl wget python build-essential
RUN curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
RUN apt-get -y install nodejs
RUN npm install webtorrent-hybrid -g
RUN apt-get -y install xvfb
ENV DISPLAY 0:99
```

Run command:
```
sudo docker run -i -t --rm=true  webtorrent-hybrid bash -c  "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & webtorrent-hybrid download \"magnet:?xt=urn:btih:a18469ae1618c3e92ed178716425bab134148836&dn=Eibriel%5FDemoReel%5F2012%5FComposition.mkv&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.istole.it%3A6969&tr=udp%3A%2F%2Ftracker.ccc.de%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337\" "
```

**Comment by feross** [comment]
I get this as well, on Linux only. Weird.

Any ideas?

**Comment by feross** [comment]
@mappum Would you happen to have any ideas?

**Comment by Eibriel** [comment]
is there any way to get more verbosity to debug the error?

**Comment by feross** [comment]
@Eibriel Not that I know of, unfortunately.

**Comment by Skeen** [comment]
+1

**Comment by mappum** [comment]
@feross Sorry for taking so long to get to this, the problem was simpler than I thought it would be. This should now be fixed when using the latest version of `electron-eval` (it's a semver patch, so just reinstall your node modules).

Note that the `xvfb` binary will need to be installed for this to run on headless Linux (although it does not need to be running, `electron-eval` will create a child process itself).

**Comment by feross** [comment]
@mappum Thanks for looking into this! Just tested it out and I'm still having issues on Linux.

Any idea why there's still an EPIPE error when running this on Linux?

```
webtorrent-hybrid seed /path/to/some/files
```

**Comment by Skeen** [comment]
I have no experience with electron, but the EPIPE error is thrown from here;

https://github.com/mappum/electron-eval/blob/master/src/index.js#L38

Commenting out this piece of code, changes the behavior from EPIPE error to hanging.

Replacing the line from `_this.stdin.write(opts)` to `console.log(opts)`; yields;
```
{ timeout: 10000, windowOpts: { show: false }, headless: true }
```

NOTE: The version pulled from NPM, and the upstream version are different, so it may actually be fixed upstream, just not published on npm?

**Comment by Skeen** [comment]
Update: I had made several changes to my setup while testing out this. When I reverted these changes and just commented above mentioned line of code out, I got webtorrent-hybrid running.

That is; comment out this single line, and everything seems to be working!

**Comment by Skeen** [comment]
I do however get a warning about EventEmitter memory leak, but this must be unrelated to the debug comment line, and can most likely be ignored.

**Comment by Skeen** [comment]
Update: It does indeed NOT seem able to seed; It enters seeding mode, but I am unable to get any data through the pipes, might be a local issue.

**Comment by mappum** [comment]
Hm, I'll look into this again, but now I'm not sure how to reproduce this since it's working for me on Linux.

**Comment by feross** [comment]
Here's my debug info:

```
DEBUG INFO: webtorrent-cli 1.2.0, webtorrent 0.94.0, node v6.1.0, linux x64, exit 1
```

Ubuntu 14.04.4 LTS

What's your setup @mappum?

**Comment by Skeen** [comment]
@feross: I have provided mappum with a faulty setup in a docker image in the linked issue.

The code in that image is 4LOC and has the same issue :)

**Comment by feross** [comment]
@Skeen Cool!

**Comment by mappum** [comment]
@feross 
```
DEBUG INFO: webtorrent-cli 1.2.0, webtorrent 0.94.0, node v6.2.0, linux x64, exit 1
```
Ubuntu 14.04.1 LTS

I'll try on a fresh server and see if it works the same.

**Comment by mappum** [comment]
Alright, I fixed multiple issues and I believe it should work now. Although I thought that last time, too 😛 

Let me know if you guys still have any problems.

**Comment by Skeen** [comment]
@mappum I have updated my referenced issue. The problem still persists, see that issue for details :)

**Comment by Skeen** [comment]
I can confirm that `webtorrent-hybrid` runs headless under `docker run -it node:argon`, with these additional packages installed;
```
apt-get install -y xvfb
apt-get install -y libnss3 libgconf2-4 libnotify4 libgtk2.0-0
```
And that it is able to seed to a web-browser via WebRTC.

**Comment by feross** [comment]
Runs without crashing for me. Thanks @mappum!

**Comment by FLYBYME** [comment]
Im getting this error. It only happens with webtorrent-hybrid but not webtorrent.

I tried installing node 4.6.0 up from 4.2.x and im running Ubuntu 16.04 LTS

**Comment by DiegoRBaquero** [comment]
@FLYBYME could you post the full error? Maybe it's a different one

**Comment by FLYBYME** [comment]
Oh it is different.. Sorry

```
Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

And I did install 
```
apt-get install -y xvfb
apt-get install -y libnss3 libgconf2-4 libnotify4 libgtk2.0-0
```
